language: minimal
dist: focal
sudo: required
virt: vm
arch: amd64
install:
  - echo "Hello world"
  - printenv
  - pwd
  - whoami
  - sudo echo "Hello root"
  - which lsusb
  - sudo ls -l /dev
  - sudo ls -l /sys/bus/usb/devices/
