language: minimal
dist: focal
sudo: required
virt: vm
install:
  - echo "Hello world"
  - printenv
  - pwd
  - whoami
  - sudo echo "Hello root"
  - which lsusb
  - sudo ls -l /dev
  - sudo ls -l /sys
  - sudo lsusb -vv
